version: '3'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: "$DATASOURCE_PASSWORD"
      MYSQL_DATABASE: "$DATASOURCE_DATABASE"
      MYSQL_USER: "$DATASOURCE_USER"
      MYSQL_PASSWORD: "$DATASOURCE_PASSWORD"
